### PR TITLE
Allow aarch64 builds

### PR DESCRIPTION
**Pull request by ananos**

### CODE REVIEW

**Comment by lumjjb** [comment]
Can you rebase master? Tks.

**Comment by lumjjb** [comment]
What we need now is to create aarch64 `.nabla` files from github.com/nabla-containers/nabla-base-build and add them to the release, and change the Makefile so that is gets the correct `.nabla` based on architecture from the release server, and we should be good!

**Comment by lumjjb** [comment]
Uploaded the `aarch64` `.nabla` files from @ananos … for `runnc` aarch64 PR, i think we can merge it in with the following changes:
- Add a `README_aarch64.md`talking about the problem, and add a link into the `README.md` at the top, to look at that document if using `aarch64`
- Have the downloaded binary for the test be based on the arch (let me know if you’d like to rename `amd64` to `x86-64`? etc.

**Comment by lumjjb** [comment]
Restarted check again. After adding `README.aarch64` and link from regular `README.md` at the top, we should be good to merge this in!

**Comment by ricarkol** [comment]
lgtm

**Pull request merged**
